/** Generated by the local Arcade Builder — closed-parameter procedural cabinet.
 * Contract: host-mounted frame, tap input only, result is a PROPOSAL (server stays authority).
 * Requests NO capabilities. Procedural drawing only — no assets, no I/O. */
export function createGame() {
  let t = 0;
  let score = 0;
  let running = false;
  const ACCENT = '#22e0ff';
  const SPEED = 2;
  const WIN = 1;   // hot-window scale (difficulty)
  const MOT = 0.7;   // motion amplitude scale (motion)
  return {
    init(f) { this.w = f.width; this.h = f.height; running = true; t = 0; score = 0; },
    tick(dt) { if (running) t += dt; },
    level() { return (Math.sin(t * SPEED) + 1) / 2; },
    hot() { return Math.abs(this.level() - 0.535) < 0.085 * WIN; },
    render(ctx) {
      const w = this.w || 360, h = this.h || 640;
      ctx.clearRect(0, 0, w, h);
      ctx.fillStyle = ACCENT; ctx.globalAlpha = 0.16;
      ctx.fillRect(0, h * (0.465 - 0.085 * WIN), w, h * 0.17 * WIN);
      ctx.globalAlpha = 0.65;
      const y = h * (1 - this.level());
      ctx.fillRect(0, y, w, h - y);
      ctx.globalAlpha = 1;
      ctx.strokeStyle = ACCENT; ctx.lineWidth = 2;
      ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(w, y); ctx.stroke();
    },
    onInput(ev) { if (!running || ev.type !== 'tap') return; if (this.hot()) score += 1; },
    proposeResult() { return { proposed_score: score, public_safe: true }; },
  };
}
