/** Generated by write-starter-statics (ADR-043) — curated starter floor adapter.
 * client_local_only · ticket_mode none · no messages, no awards, no authority.
 * BYTE-PINNED to the generator by unit test — do not hand-edit. */
import { createGame as createCabinetGame } from './game.mjs';
import { starterAdapter, starterContract, createStarterHostGame } from '../starter-host.mjs';

export const adapter = starterAdapter('starter_crosswalk_window', 'Crosswalk Window');
export const contract = starterContract('starter_crosswalk_window', 'Crosswalk Window');
export function createGame(opts) {
  return createStarterHostGame({ createCabinetGame, displayName: 'Crosswalk Window', instruction: 'Tap at the right moment.', sound: 'off', onLeave: opts && opts.onLeave });
}
