/** Generated by the local Arcade Builder — closed-parameter procedural cabinet.
 * Contract: host-mounted frame, tap input only, result is a PROPOSAL (server stays authority).
 * Requests NO capabilities. Procedural drawing only — no assets, no I/O. */
export function createGame() {
  let t = 0;
  let score = 0;
  let running = false;
  const ACCENT = '#22e0ff';
  const SPEED = 2;
  const WIN = 1;   // hot-window scale (difficulty)
  const MOT = 1;   // motion amplitude scale (motion)
  return {
    init(f) { this.w = f.width; this.h = f.height; running = true; t = 0; score = 0; },
    tick(dt) { if (running) t += dt; },
    frac() { return (t * SPEED * 0.5) % 1; },
    hot() { const f = this.frac(); return f > 0.62 && f < 0.62 + 0.14 * WIN; },
    render(ctx) {
      const w = this.w || 360, h = this.h || 640;
      ctx.clearRect(0, 0, w, h);
      ctx.fillStyle = ACCENT; ctx.globalAlpha = 0.14;
      ctx.fillRect(0, h * 0.4, w, h * 0.2);
      ctx.globalAlpha = 0.5;
      for (let i = 0; i < 6; i++) ctx.fillRect(w * (0.08 + i * 0.15), h * 0.44, w * 0.07, h * 0.12);
      ctx.globalAlpha = 1;
      ctx.beginPath(); ctx.arc(w / 2, h * 0.25, 14, 0, Math.PI * 2);
      ctx.strokeStyle = ACCENT; ctx.lineWidth = 3;
      if (this.hot()) { ctx.fillStyle = ACCENT; ctx.fill(); } else { ctx.stroke(); }
    },
    onInput(ev) { if (!running || ev.type !== 'tap') return; if (this.hot()) score += 1; },
    proposeResult() { return { proposed_score: score, public_safe: true }; },
  };
}
