/**
 * Creator Foundation — LOCAL Arcade Builder (cabinet composer; trusted, offline).
 *
 * The assembled-builder UX over the EXISTING CF pipeline: pick one of three closed procedural game
 * variants, tune closed parameters (accent / speed / frame contract / size budget), and the builder
 * GENERATES a complete `arcade_game` package — manifest.json + game.mjs + adapter.mjs — then runs it
 * through the SAME gate the importer uses (importArcadePackage: manifest validation + code-aware
 * source scan + size budget + frame contract). Export = three file downloads.
 *
 * DATA-ONLY by design: this page NEVER executes the generated game (no eval, no dynamic import) —
 * running creator code is the arcade-sandbox's job (srcdoc iframe + closed CSP). All substitution
 * values come from CLOSED token tables, and the importer's scan re-checks the output regardless.
 * No submit, no upload, no live registration. See arcade/virtual-arcade/HIVE_WORLD_ALIGNMENT.md §5.
 */
import { importArcadePackage, FRAME_CONTRACT_DIMS } from '../arcade-importer/import-arcade-package.mjs';
import { FRAME_CONTRACTS, SIZE_BUDGET_MIN_BYTES, SIZE_BUDGET_MAX_BYTES, SCHEMA_VERSION, PACKAGE_KIND } from '../schemas/arcade-game-package-schema.mjs';

const el = (id) => document.getElementById(id);

// ── closed parameter tables (the ONLY values that reach generated source) ─────
const ACCENTS = Object.freeze({
  cyan: '#22e0ff', magenta: '#ff2d95', violet: '#b14aff', green: '#3df58b', amber: '#ff9e3f',
});
const SPEEDS = Object.freeze({ slow: '1.2', medium: '2', fast: '3.2' });
const VARIANTS = Object.freeze(['pulse-ring', 'drift-band', 'tri-light']);

// ── generated sources (no template literals in OUTPUT — the importer scans them) ──
// Each variant follows the SDK contract verbatim: init/tick/render/onInput/proposeResult,
// 'tap' input only, result is an advisory proposal, zero capabilities.
function gameSource(variant, accentHex, speed) {
  const head = [
    '/** Generated by the local Arcade Builder — closed-parameter procedural cabinet.',
    ' * Contract: host-mounted frame, tap input only, result is a PROPOSAL (server stays authority).',
    ' * Requests NO capabilities. Procedural drawing only — no assets, no I/O. */',
    'export function createGame() {',
    '  let t = 0;',
    '  let score = 0;',
    '  let running = false;',
    "  const ACCENT = '" + accentHex + "';",
    '  const SPEED = ' + speed + ';',
  ].join('\n');
  const tail = [
    "    onInput(ev) { if (!running || ev.type !== 'tap') return; if (this.hot()) score += 1; },",
    '    proposeResult() { return { proposed_score: score, public_safe: true }; },',
    '  };',
    '}',
  ].join('\n');
  if (variant === 'drift-band') {
    return head + '\n' + [
      '  return {',
      '    init(f) { this.w = f.width; this.h = f.height; running = true; t = 0; score = 0; },',
      '    tick(dt) { if (running) t += dt; },',
      '    hot() { const x = (Math.sin(t * SPEED) + 1) / 2; return x > 0.4 && x < 0.6; },',
      '    render(ctx) {',
      '      const w = this.w || 360, h = this.h || 640;',
      '      ctx.clearRect(0, 0, w, h);',
      '      ctx.fillStyle = ACCENT; ctx.globalAlpha = 0.18;',
      '      ctx.fillRect(w * 0.4, 0, w * 0.2, h);',
      '      ctx.globalAlpha = 1;',
      '      const x = w * ((Math.sin(t * SPEED) + 1) / 2);',
      '      ctx.beginPath(); ctx.arc(x, h / 2, 14, 0, Math.PI * 2); ctx.fillStyle = ACCENT; ctx.fill();',
      '    },',
    ].join('\n') + '\n' + tail;
  }
  if (variant === 'tri-light') {
    return head + '\n' + [
      '  return {',
      '    init(f) { this.w = f.width; this.h = f.height; running = true; t = 0; score = 0; },',
      '    tick(dt) { if (running) t += dt; },',
      '    lit() { return Math.floor(t * SPEED) % 3; },',
      '    hot() { return this.lit() === 1; },',
      '    render(ctx) {',
      '      const w = this.w || 360, h = this.h || 640;',
      '      ctx.clearRect(0, 0, w, h);',
      '      for (let i = 0; i < 3; i++) {',
      '        ctx.beginPath(); ctx.arc(w * (0.25 + i * 0.25), h / 2, 22, 0, Math.PI * 2);',
      '        ctx.strokeStyle = ACCENT; ctx.lineWidth = 3;',
      '        if (i === this.lit()) { ctx.fillStyle = ACCENT; ctx.fill(); } else { ctx.stroke(); }',
      '      }',
      '    },',
    ].join('\n') + '\n' + tail;
  }
  // default: pulse-ring (the SDK reference loop, parameterized)
  return head + '\n' + [
    '  return {',
    '    init(f) { this.w = f.width; this.h = f.height; running = true; t = 0; score = 0; },',
    '    tick(dt) { if (running) t += dt; },',
    '    hot() { return Math.abs(Math.sin(t * SPEED)) > 0.85; },',
    '    render(ctx) {',
    '      const w = this.w || 360, h = this.h || 640;',
    '      const r = 30 + 18 * Math.abs(Math.sin(t * SPEED));',
    '      ctx.clearRect(0, 0, w, h);',
    '      ctx.strokeStyle = ACCENT; ctx.lineWidth = 3;',
    '      ctx.beginPath(); ctx.arc(w / 2, h / 2, r, 0, Math.PI * 2); ctx.stroke();',
    '    },',
  ].join('\n') + '\n' + tail;
}

function adapterSource() {
  return [
    '/** Generated by the local Arcade Builder — the SDK reference adapter, verbatim contract.',
    ' * The ONLY bridge between the sandboxed game and the host frame. No network, no storage,',
    ' * no authority — results are PROPOSED to the host; the server validates/awards. */',
    "import { createGame } from './game.mjs';",
    '',
    'export function createAdapter() {',
    '  const game = createGame();',
    '  return {',
    '    mount(frame) { game.init({ width: frame.width, height: frame.height }); },',
    '    frame(dt, ctx) { game.tick(dt); game.render(ctx); },',
    '    input(ev) { game.onInput(ev); },',
    '    result() { return game.result ? game.result() : game.proposeResult(); },',
    '    capabilities() { return []; },',
    '  };',
    '}',
  ].join('\n');
}

// ── build + gate + report ─────────────────────────────────────────────────────
const state = { lastReport: null, lastBuild: null };

function build() {
  const variant = VARIANTS.includes(el('variant').value) ? el('variant').value : VARIANTS[0];
  const accent = ACCENTS[el('accent').value] || ACCENTS.cyan;
  const speed = SPEEDS[el('speed').value] || SPEEDS.medium;
  const manifest = {
    schema_version: SCHEMA_VERSION,
    package_kind: PACKAGE_KIND,
    package_id: String(el('packageId').value || ''),
    display_name: String(el('displayName').value || '').trim() || 'Untitled Cabinet',
    frame_contract_id: el('frame').value,
    entry: 'game.mjs',
    adapter: 'adapter.mjs',
    assets: [],
    capabilities: [],
    size_budget_bytes: Number(el('budget').value) || SIZE_BUDGET_MIN_BYTES,
  };
  const files = {
    'game.mjs': gameSource(variant, accent, speed),
    'adapter.mjs': adapterSource(),
  };
  return { manifest, files, variant };
}

function drawFramePreview(report, buildOut) {
  const canvas = el('framePreview');
  const ctx = canvas.getContext('2d');
  ctx.clearRect(0, 0, canvas.width, canvas.height);
  ctx.fillStyle = '#05060c'; ctx.fillRect(0, 0, canvas.width, canvas.height);
  const dims = report.frame_dims || FRAME_CONTRACT_DIMS[buildOut.manifest.frame_contract_id];
  if (!dims) return;
  const scale = Math.min((canvas.width - 24) / dims.width, (canvas.height - 24) / dims.height);
  const w = dims.width * scale, h = dims.height * scale;
  const x = (canvas.width - w) / 2, y = (canvas.height - h) / 2;
  const accent = ACCENTS[el('accent').value] || ACCENTS.cyan;
  ctx.strokeStyle = accent; ctx.lineWidth = 2; ctx.strokeRect(x, y, w, h);
  ctx.fillStyle = accent; ctx.font = '11px monospace'; ctx.textAlign = 'center';
  ctx.fillText(`${dims.width}×${dims.height} · ${buildOut.variant}`, canvas.width / 2, y + h + 14);
}

function refresh() {
  const out = build();
  state.lastBuild = out;
  const report = importArcadePackage({ manifest: out.manifest, files: out.files });
  state.lastReport = report;
  const verdict = el('verdict');
  verdict.textContent = report.ok ? 'VALID (untrusted local proposal)' : 'BLOCKED';
  verdict.className = 'verdict ' + (report.ok ? 'v-ok' : 'v-bad');
  el('issues').textContent = report.errors.length ? report.errors.join('\n') : '(none)';
  el('sizes').textContent = `${report.limits.total_bytes} / ${report.limits.size_budget_bytes} bytes · trust=${report.result_trust}`;
  el('exportAll').disabled = !report.ok;
  el('srcView').textContent = out.files['game.mjs'];
  drawFramePreview(report, out);
}

function download(name, text, type) {
  const blob = new Blob([text], { type: type || 'text/javascript' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = name;
  a.click();
  URL.revokeObjectURL(a.href);
}

function wire() {
  for (const id of ['packageId', 'displayName']) el(id).addEventListener('input', refresh);
  for (const id of ['variant', 'accent', 'speed', 'frame', 'budget']) el(id).addEventListener('change', refresh);
  el('exportAll').addEventListener('click', () => {
    if (!state.lastBuild || !state.lastReport?.ok) return;
    const { manifest, files } = state.lastBuild;
    download('manifest.json', JSON.stringify(manifest, null, 2), 'application/json');
    download('game.mjs', files['game.mjs']);
    download('adapter.mjs', files['adapter.mjs']);
  });
  // closed select options come from the closed tables — single source of truth
  for (const v of VARIANTS) { const o = document.createElement('option'); o.value = v; o.textContent = v; el('variant').appendChild(o); }
  for (const k of Object.keys(ACCENTS)) { const o = document.createElement('option'); o.value = k; o.textContent = k; el('accent').appendChild(o); }
  for (const k of Object.keys(SPEEDS)) { const o = document.createElement('option'); o.value = k; o.textContent = k; el('speed').appendChild(o); }
  for (const f of FRAME_CONTRACTS) { const o = document.createElement('option'); o.value = f; o.textContent = f; el('frame').appendChild(o); }
  el('speed').value = 'medium';
  refresh();
}
if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', wire); else wire();

// ── test/automation hook (mirrors the other CF tools) ────────────────────────
window.__cf_builder = {
  get lastReport() { return state.lastReport; },
  get lastBuild() { return state.lastBuild; },
  refresh,
};
