/** Generated by write-starter-statics (ADR-043) — curated starter floor adapter.
 * client_local_only · ticket_mode none · no messages, no awards, no authority.
 * BYTE-PINNED to the generator by unit test — do not hand-edit. */
import { createGame as createCabinetGame } from './game.mjs';
import { starterAdapter, starterContract, createStarterHostGame } from '../starter-host.mjs';

export const adapter = starterAdapter('starter_beacon_climb', 'Beacon Climb');
export const contract = starterContract('starter_beacon_climb', 'Beacon Climb');
export function createGame(opts) {
  return createStarterHostGame({ createCabinetGame, displayName: 'Beacon Climb', instruction: 'Hold while the moment is right.', onLeave: opts && opts.onLeave });
}
