/** Generated by the local Arcade Builder — closed-parameter procedural cabinet.
 * Contract: host-mounted frame, tap input only, result is a PROPOSAL (server stays authority).
 * Requests NO capabilities. Procedural drawing only — no assets, no I/O. */
export function createGame() {
  let t = 0;
  let score = 0;
  let running = false;
  const ACCENT = '#ff9e3f';
  const SPEED = 2;
  const WIN = 1;   // hot-window scale (difficulty)
  const MOT = 1;   // motion amplitude scale (motion)
  return {
    init(f) { this.w = f.width; this.h = f.height; running = true; t = 0; score = 0; },
    tick(dt) { if (running) t += dt; },
    rung() { return Math.floor(t * SPEED * 2) % 6; },
    hot() { return this.rung() === 5; },
    render(ctx) {
      const w = this.w || 360, h = this.h || 640;
      ctx.clearRect(0, 0, w, h);
      for (let i = 0; i < 6; i++) {
        const y = h * 0.82 - i * h * 0.12;
        ctx.strokeStyle = ACCENT; ctx.lineWidth = i === 5 ? 3 : 2;
        ctx.beginPath(); ctx.arc(w / 2, y, i === 5 ? 16 : 11, 0, Math.PI * 2);
        if (i === this.rung()) { ctx.fillStyle = ACCENT; ctx.fill(); } else { ctx.stroke(); }
      }
    },
    onInput(ev) { if (!running || ev.type !== 'tap') return; if (this.hot()) score += 1; },
    proposeResult() { return { proposed_score: score, public_safe: true }; },
  };
}
