/** Generated by write-starter-statics (ADR-043) — curated starter floor adapter.
 * client_local_only · ticket_mode none · no messages, no awards, no authority.
 * BYTE-PINNED to the generator by unit test — do not hand-edit. */
import { createGame as createCabinetGame } from './game.mjs';
import { starterAdapter, starterContract, createStarterHostGame } from '../starter-host.mjs';

export const adapter = starterAdapter('starter_phase_lock', 'Phase Lock');
export const contract = starterContract('starter_phase_lock', 'Phase Lock');
export function createGame(opts) {
  return createStarterHostGame({ createCabinetGame, displayName: 'Phase Lock', instruction: 'Keep your pointer moving with it.', sound: 'off', onLeave: opts && opts.onLeave });
}
