/** Generated by the local Arcade Builder — closed-parameter procedural cabinet.
 * Contract: host-mounted frame, tap input only, result is a PROPOSAL (server stays authority).
 * Requests NO capabilities. Procedural drawing only — no assets, no I/O. */
export function createGame() {
  let t = 0;
  let score = 0;
  let running = false;
  const ACCENT = '#b14aff';
  const SPEED = 1.2;
  const WIN = 1.5;   // hot-window scale (difficulty)
  const MOT = 1;   // motion amplitude scale (motion)
  return {
    init(f) { this.w = f.width; this.h = f.height; running = true; t = 0; score = 0; },
    tick(dt) { if (running) t += dt; },
    diff() {
      const d = Math.abs(((t * SPEED * 0.7 + t * SPEED * 0.53) % (Math.PI * 2)));
      return Math.min(d, Math.PI * 2 - d);
    },
    hot() { return this.diff() < 0.3 * WIN; },
    render(ctx) {
      const w = this.w || 360, h = this.h || 640;
      const cx = w / 2, cy = h / 2;
      const R1 = Math.min(w, h) * 0.3, R2 = Math.min(w, h) * 0.19;
      ctx.clearRect(0, 0, w, h);
      ctx.strokeStyle = ACCENT; ctx.lineWidth = 2;
      ctx.beginPath(); ctx.arc(cx, cy, R1, 0, Math.PI * 2); ctx.stroke();
      ctx.beginPath(); ctx.arc(cx, cy, R2, 0, Math.PI * 2); ctx.stroke();
      const a1 = t * SPEED * 0.7, a2 = -t * SPEED * 0.53;
      ctx.fillStyle = ACCENT;
      ctx.beginPath(); ctx.arc(cx + Math.cos(a1) * R1, cy + Math.sin(a1) * R1, 8, 0, Math.PI * 2); ctx.fill();
      ctx.beginPath(); ctx.arc(cx + Math.cos(a2) * R2, cy + Math.sin(a2) * R2, 8, 0, Math.PI * 2); ctx.fill();
      if (this.hot()) {
        ctx.beginPath(); ctx.moveTo(cx + Math.cos(a1) * R1, cy + Math.sin(a1) * R1);
        ctx.lineTo(cx + Math.cos(a2) * R2, cy + Math.sin(a2) * R2); ctx.stroke();
      }
    },
    onInput(ev) { if (!running || ev.type !== 'tap') return; if (this.hot()) score += 1; },
    proposeResult() { return { proposed_score: score, public_safe: true }; },
  };
}
