/** Generated by the local Arcade Builder — closed-parameter procedural cabinet.
 * Contract: host-mounted frame, tap input only, result is a PROPOSAL (server stays authority).
 * Requests NO capabilities. Procedural drawing only — no assets, no I/O. */
export function createGame() {
  let t = 0;
  let score = 0;
  let running = false;
  const ACCENT = '#3df58b';
  const SPEED = 1.2;
  const WIN = 1.5;   // hot-window scale (difficulty)
  const MOT = 0.7;   // motion amplitude scale (motion)
  return {
    init(f) { this.w = f.width; this.h = f.height; running = true; t = 0; score = 0; },
    tick(dt) { if (running) t += dt; },
    bloom() { return (Math.sin(t * SPEED) + 1) / 2; },
    hot() { return this.bloom() > 1 - 0.18 * WIN; },
    render(ctx) {
      const w = this.w || 360, h = this.h || 640;
      const cx = w / 2, cy = h / 2, b = this.bloom();
      ctx.clearRect(0, 0, w, h);
      ctx.strokeStyle = ACCENT;
      for (let i = 1; i <= 3; i++) {
        ctx.globalAlpha = 0.9 - i * 0.22;
        ctx.lineWidth = 4 - i;
        ctx.beginPath(); ctx.arc(cx, cy, 14 + b * MOT * 26 * i, 0, Math.PI * 2); ctx.stroke();
      }
      ctx.globalAlpha = 1;
    },
    onInput(ev) { if (!running || ev.type !== 'tap') return; if (this.hot()) score += 1; },
    proposeResult() { return { proposed_score: score, public_safe: true }; },
  };
}
