/** Generated by the local Arcade Builder — closed-parameter procedural cabinet.
 * Contract: host-mounted frame, pointer/tap input, result is a PROPOSAL (server stays authority).
 * Requests NO capabilities. Procedural drawing only — no assets, no I/O, no timers. */
export function createGame() {
  let t = 0;
  let score = 0;
  let running = false;
  let held = false, heldHot = 0, downX = 0, downT = 0, moveAt = 0, moved = false;
  const ACCENT = '#ff2d95';
  const SPEED = 1.2;
  const WIN = 1.5;   // hot-window scale (difficulty)
  const MOT = 1.3;   // motion amplitude scale (motion)
  const MODE = 'tap_window';
  const HOLD_CAD = 0.3, DRAG_CAD = 0.35;
  const DRAG_WIN = 0.4, SWIPE_PX = 64, SWIPE_T = 0.6;
  // visual feel: fixed pool, decay-only state, reduced-motion clamps to 0 (no shake ever)
  const RM = typeof matchMedia === "function" && matchMedia("(prefers-reduced-motion: reduce)").matches;
  const FX = RM ? 0 : 2;
  const FXN = FX ? 48 : 0;
  const px = [], py = [], pvx = [], pvy = [], pl = [];
  let fi = 0, flash = 0, shake = 0;
  function fxBurst(cx, cy) {
    if (!FXN) return;
    for (let i = 0; i < 8; i++) {
      const a = (i / 8) * Math.PI * 2;
      px[fi] = cx; py[fi] = cy; pvx[fi] = Math.cos(a) * 90; pvy[fi] = Math.sin(a) * 90; pl[fi] = 0.5;
      fi = (fi + 1) % FXN;
    }
    flash = 0.22;
    if (FX > 1) shake = 0.28;
  }
  function fxStep(dt) {
    for (let i = 0; i < FXN; i++) if (pl[i] > 0) { pl[i] -= dt; px[i] += pvx[i] * dt; py[i] += pvy[i] * dt; }
    if (flash > 0) flash -= dt;
    if (shake > 0) shake -= dt;
  }
  function fxDraw(ctx, w, h) {
    if (!FXN) return;
    ctx.save(); ctx.fillStyle = ACCENT;
    for (let i = 0; i < FXN; i++) if (pl[i] > 0) { ctx.globalAlpha = Math.max(0, Math.min(1, pl[i] * 2)); ctx.fillRect(px[i] - 2, py[i] - 2, 4, 4); }
    if (flash > 0) { ctx.globalAlpha = flash * 0.5; ctx.fillRect(0, 0, w, h); }
    ctx.restore();
  }
  return {
    init(f) {
      this.w = f.width; this.h = f.height; running = true; t = 0; score = 0;
      held = false; heldHot = 0; fi = 0; flash = 0; shake = 0;
      for (let i = 0; i < FXN; i++) { px[i] = 0; py[i] = 0; pvx[i] = 0; pvy[i] = 0; pl[i] = 0; }
    },
    tick(dt) {
      if (!running) return;
      t += dt;
      fxStep(dt);
      if (MODE === 'hold_band' || MODE === 'drag_track') {
        const cad = MODE === 'hold_band' ? HOLD_CAD : DRAG_CAD;
        const engaged = MODE === 'hold_band' ? held : (held && moved && (t - moveAt) < DRAG_WIN);
        if (engaged && this.hot()) {
          heldHot += dt;
          if (heldHot >= cad) { heldHot -= cad; score += 1; fxBurst((this.w || 360) / 2, (this.h || 640) / 2); }
        } else if (!engaged) {
          heldHot = 0;  // leaving the gesture resets accrual — no banked fractions
        }
      }
    },
    hot() { return Math.abs(Math.sin(t * SPEED)) > 1 - 0.15 * WIN; },
    scene(ctx) {
      const w = this.w || 360, h = this.h || 640;
      const r = 30 + 18 * MOT * Math.abs(Math.sin(t * SPEED));
      ctx.clearRect(0, 0, w, h);
      ctx.strokeStyle = ACCENT; ctx.lineWidth = 3;
      ctx.beginPath(); ctx.arc(w / 2, h / 2, r, 0, Math.PI * 2); ctx.stroke();
    },
    onInput(ev) {
      if (!running || !ev) return;
      const cx = typeof ev.x === "number" ? ev.x : (this.w || 360) / 2;
      const cy = typeof ev.y === "number" ? ev.y : (this.h || 640) / 2;
      const hit = () => { score += 1; fxBurst(cx, cy); };
      if (ev.type === 'tap') { if (this.hot()) hit(); return; } // degenerate press+release: every mode
      if (ev.type === 'press') {
        held = true; downX = cx; downT = t; moveAt = t; moved = false;
        if (MODE === 'tap_window' && this.hot()) hit();
        return;
      }
      if (ev.type === 'move') { if (held) { moveAt = t; moved = true; } return; }
      if (ev.type === 'release') {
        if (!held) return;
        held = false;
        if (MODE === 'release_timing' && this.hot()) hit();
        if (MODE === 'swipe_lane' && Math.abs(cx - downX) >= SWIPE_PX && (t - downT) <= SWIPE_T && this.hot()) hit();
      }
    },
    render(ctx) {
      const w = this.w || 360, h = this.h || 640;
      ctx.save();
      if (shake > 0) ctx.translate(Math.sin(t * 70) * shake * 8, Math.cos(t * 60) * shake * 6);
      this.scene(ctx);
      ctx.restore();
      fxDraw(ctx, w, h);
    },
    proposeResult() { return { proposed_score: score, public_safe: true }; },
  };
}
