/** Generated by the local Arcade Builder — closed-parameter procedural cabinet.
 * Contract: host-mounted frame, tap input only, result is a PROPOSAL (server stays authority).
 * Requests NO capabilities. Procedural drawing only — no assets, no I/O. */
export function createGame() {
  let t = 0;
  let score = 0;
  let running = false;
  const ACCENT = '#ff2d95';
  const SPEED = 3.2;
  const WIN = 0.65;   // hot-window scale (difficulty)
  const MOT = 1;   // motion amplitude scale (motion)
  return {
    init(f) { this.w = f.width; this.h = f.height; running = true; t = 0; score = 0; },
    tick(dt) { if (running) t += dt; },
    level() { return (Math.sin(t * SPEED) * MOT * 0.9 + 1) / 2; },
    hot() { return Math.abs(this.level() - 0.5) < 0.09 * WIN; },
    render(ctx) {
      const w = this.w || 360, h = this.h || 640;
      const cx = w / 2, cy = h * 0.62, R = Math.min(w, h) * 0.34;
      ctx.clearRect(0, 0, w, h);
      ctx.strokeStyle = ACCENT; ctx.lineWidth = 3;
      ctx.beginPath(); ctx.arc(cx, cy, R, Math.PI, Math.PI * 2); ctx.stroke();
      ctx.globalAlpha = 0.2; ctx.lineWidth = 12;
      const mid = Math.PI * 1.5;
      ctx.beginPath(); ctx.arc(cx, cy, R, mid - 0.28 * WIN, mid + 0.28 * WIN); ctx.stroke();
      ctx.globalAlpha = 1; ctx.lineWidth = 3;
      const a = Math.PI + this.level() * Math.PI;
      ctx.beginPath(); ctx.moveTo(cx, cy);
      ctx.lineTo(cx + Math.cos(a) * R * 0.85, cy + Math.sin(a) * R * 0.85); ctx.stroke();
    },
    onInput(ev) { if (!running || ev.type !== 'tap') return; if (this.hot()) score += 1; },
    proposeResult() { return { proposed_score: score, public_safe: true }; },
  };
}
